# -*- coding: utf-8 -*-
"""Heroku.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bbNVUA7LicNdrTOHDzVGQG7nZkTf4hPH
"""

#from google.colab import drive
#drive.mount('/drive')

#cd /drive/MyDrive/Flask

import numpy as np
from flask import Flask, request, render_template
import pickle

app = Flask(__name__)
model = pickle.load(open('weight_pred_model.pkl', 'rb'))

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/getprediction',methods=['POST'])
def getprediction():    

    input = [float(x) for x in request.form.values()]
    final_input = [np.array(input)]
    prediction = model.predict(final_input)

    return render_template('index.html', output='Predicted Crop Yield:{}'.format(prediction))

#def getprediction(text_box_1,text_box_2,text_box_3,text_box_4,text_box_5,text_box_6,text_box_7,text_box_8,text_box_9,text_box_10,text_box_11,text_box_12,text_box_13,text_box_14,text_box_15,text_box_16,text_box_17):
  #classification = model.predict([[text_box_1,text_box_2,text_box_3,text_box_4,text_box_5,text_box_6,text_box_7,text_box_8,text_box_9,text_box_10,text_box_11,text_box_12,text_box_13,text_box_14,text_box_15,text_box_16,text_box_17]])
  #return classification[0]

if __name__ == "__main__":
    app.run(debug=True)
#app.run()

    
#if __name__ == '__main__':
    # Bind to PORT if defined, otherwise default to 5000.
 #   port = int(os.environ.get('PORT', 5000))
  #  app.run(host='0.0.0.0', port=port)
